Change backgroundAlternative to darkModeBlack
Telefonica/mistica-design pull request #1128
Opened 2023-03-15 10:28 UTC by aweell

### 🎟 Jira Ticket

**Merge blocked until all platforms works on it**
### 🧑‍💻 Development status
- [ ] Android — 
- [ ] iOS — 
- [ ] Web —

2023-03-27 13:06 UTC, yceballost approved these changes
✨

2023-03-28 20:05 UTC, yceballost commented
can you add vivo-new? 😇

2023-04-12 08:15 UTC, aweell commented
> can you add vivo-new? 😇

Done

2023-04-12 20:51 UTC, yceballost requested changes

2023-04-12 20:51 UTC, yceballost commented on tokens/blau.json
> +      "description": "movistarBlue"
```suggestion
      "description": "blauBluePrimary"
```

2023-04-13 11:26 UTC, AnaMontes11 approved these changes

2023-04-13 11:26 UTC, AnaMontes11 commented on tokens/blau.json
> +      "description": "movistarBlue"
Change it to "blauBluePrimary"

2023-04-14 08:45 UTC, yceballost approved these changes

2023-04-14 08:47 UTC, merged