Add new interaction tokens + update skin schema
Telefonica/mistica-design pull request #1206
Opened 2023-04-25 14:32 UTC by aweell

![tokens-states](https://user-images.githubusercontent.com/44420072/235883857-f252df03-3b33-4e17-95e9-5badcdf08944.png)

Solves:
* https://github.com/Telefonica/mistica-design/issues/1202
* https://github.com/Telefonica/mistica-design/issues/1204

2023-04-27 16:01 UTC, yceballost commented on tokens/blau.json
> +    "backgroundContainerBrandPressedOverInverse": {
Should the state be at the end of the token name? 🤔

2023-04-27 18:01 UTC, aweell commented on tokens/blau.json
> +    "backgroundContainerBrandPressedOverInverse": {
Yes, I updated following the semantics of other tokens with state + themevariant

2023-05-03 08:40 UTC, yceballost approved these changes

2023-05-03 13:28 UTC, AnaMontes11 commented on tokens/o2.json
> +      "description": "darkModeGrey"
Change description to "darkModeGrey7"

2023-05-03 13:28 UTC, AnaMontes11 commented on tokens/o2.json
> +      "description": "darkModeGrey"
change description to "darkModeGrey8"

2023-05-03 14:57 UTC, AnaMontes11 approved these changes
Really nice!

2023-05-03 16:12 UTC, yceballost requested changes

2023-05-03 16:12 UTC, yceballost commented on tokens/telefonica.json
> +      "description": "darkModeGrey8"
seems wrong

2023-05-03 20:59 UTC, yceballost approved these changes
letsss goooo!

2023-05-04 06:12 UTC, merged