Tokens for designers guide
Telefonica/mistica-design pull request #1359
Opened 2023-07-07 13:30 UTC by aweell

Introduces a new guide called "Tokens for designers" to facilitate contributions from designers working with different brands. The guide provides step-by-step instructions on how to make changes to the token files specific to each brand.

The guide covers the following topics:
- Installing a text editor (VSCode is recommended)
- Installing GitHub Desktop for managing the repository
- Cloning the repository and opening it in VS Code
- Creating a new branch for making changes
- Modifying the JSON files for colors, constants, and border radius
- Saving changes and publishing the branch

By providing this guide, we aim to empower designers from different brands to contribute to the Mistica design system more easily. This will help improve the customization and flexibility of the system based on specific brand requirements.

This change adds valuable documentation and enhances the collaboration process between designers and the Mistica design system.

2023-07-14 08:18 UTC, yceballost commented on guides/colors-contribution.md
No crees que hacer la gestión por VSCODE del tema commits es más complejo que hacerlo por GitHub Desktop? Pensando en diseñadores creo que es menos ruidoso

2023-07-14 08:31 UTC, yceballost requested changes

2023-07-14 08:31 UTC, yceballost commented on guides/colors-contribution.md
> +3. Comprueba que la rama base es `pre-production` y que la rama que estás comparando es la que acabas de crear
realmente lo más seguro es que siempre hagan la rama desde `production`, no?

2023-07-20 13:45 UTC, aweell commented on guides/colors-contribution.md
He añadido los pasos para GitHub desktop también, así quien quiera lo hace en uno u otro

2023-08-08 17:04 UTC, aweell commented on guides/colors-contribution.md
> +3. Comprueba que la rama base es `pre-production` y que la rama que estás comparando es la que acabas de crear
Añadida una nota y como crear desde production en vez de que se te cree automáticamente desde main

2023-08-17 14:20 UTC, yceballost requested changes

2023-08-17 14:20 UTC, yceballost commented on guides/colors-contribution.md
> +<img width="286" alt="Screenshot 2023-07-06 at 17 39 09" src="https://github.com/Telefonica/mistica-design/assets/44420072/198dc196-c236-4855-abe4-d2adc38b30c0">
why not markdown syntax? width?

2023-08-17 14:20 UTC, yceballost commented on guides/colors-contribution.md
> +<img width="286" alt="Screenshot 2023-07-06 at 17 39 09" src="https://github.com/Telefonica/mistica-design/assets/44420072/198dc196-c236-4855-abe4-d2adc38b30c0">
Should we host this images in repo? in resources folder 🤔

2023-08-17 14:20 UTC, yceballost commented on guides/colors-contribution.md
> +If you need to change the production branch
this text looks weird, like isolated
![image](https://github.com/Telefonica/mistica-design/assets/6722153/887d3cf7-5079-4b03-9445-8560582181b4)

2023-08-17 18:53 UTC, yceballost commented on guides/colors-contribution.md
rename to `tokens-contribution.md`

2023-11-06 11:55 UTC, aweell commented on guides/colors-contribution.md
> +<img width="286" alt="Screenshot 2023-07-06 at 17 39 09" src="https://github.com/Telefonica/mistica-design/assets/44420072/198dc196-c236-4855-abe4-d2adc38b30c0">
This is to avoid the images to take the whole screen if they can and adapt them a little bit to the intended size

2023-11-06 15:19 UTC, aweell commented on guides/colors-contribution.md
> +<img width="286" alt="Screenshot 2023-07-06 at 17 39 09" src="https://github.com/Telefonica/mistica-design/assets/44420072/198dc196-c236-4855-abe4-d2adc38b30c0">
Done, in order to use them with the correct url we need to merge first this PR

2023-11-06 15:21 UTC, yceballost approved these changes

2023-11-06 16:15 UTC, merged