text-secondary-inverse
Telefonica/mistica-design pull request #896
Opened 2022-11-11 12:31 UTC by AnaMontes11

Ready to review for all brands

2022-11-18 10:11 UTC, aweell approved these changes

2022-11-18 17:14 UTC, yceballost requested changes
can you include an image of each combination with all brands in the PR description?

2022-11-21 08:46 UTC, AnaMontes11 commented
> ¿Puedes incluir una imagen de cada combinación con todas las marcas en la descripción de relaciones públicas?

done

2022-11-21 09:05 UTC, yceballost commented on tokens/vivo.json
> +      "value": "{palette.grey3}",
why did you make this change?

2022-11-21 09:20 UTC, AnaMontes11 commented on tokens/vivo.json
> +      "value": "{palette.grey3}",
fixed

2022-11-21 13:56 UTC, yceballost approved these changes
nice!

2022-12-13 14:16 UTC, merged